extends SceneTree

# Regression suite for "the Call Trump screen was still up behind the Nello
# exchange". See Spec_picker_panel_reset_Aug1_2026.md.
#
# The bug: the four bidding-flow pickers are each opened and closed only by their
# own handlers, and _start_hand() never touched them. A picker abandoned
# mid-decision — Settings -> Play while Call Trump is up — stayed visible into the
# next hand, where it stacked above that hand's picker in play_vbox and pushed the
# lower one's controls off the bottom of a short window.
#
# Two fixes are pinned here:
#   * _close_all_pickers() at the top of _start_hand()  — the reset.
#   * _close_pickers_except() in each _show_*_panel()   — exclusivity.
#
# Leak checks assert on trump/nello/exchange only, never on bid_panel: a fresh
# hand may legitimately reopen bid_panel inside the restart when the human bids
# first, so "bid_panel is closed" is not a sound assertion. The other three cannot
# legitimately be open during a new auction.
#
# Everything runs in ONE frame on purpose. Panel visibility is set synchronously,
# while _run_bidding_sequence() parks on real-time timers — letting frames elapse
# would let an AI bid land mid-suite and open a picker for legitimate reasons.
#
# Snapshots and restores user:// (see Headless_Harness_Reference.md gotcha #9).
#
# EXPECTED on stderr: "ObjectDB instances leaked at exit". Each restart leaves a
# bidding coroutine parked on a timer that is still suspended at exit, and this
# suite performs several. Benign. Judge the exit code and the results JSON.

const BidScript = preload("res://bid.gd")

const TOUCHED_PATHS := [
	"user://last_used.json",
	"user://display_prefs.json",
	"user://preset_overrides/teel.json",
	"user://slot_names.json",
	"user://custom_rulesets/Custom.json",
]
var _snapshot: Dictionary = {}
var _table: Node = null
var _frame := 0
var _results: Array = []
var _failures := 0

func _check(name: String, ok: bool, detail: String = "") -> void:
	_results.append({"test": name, "pass": ok, "detail": detail})
	if not ok:
		_failures += 1

func _snapshot_user_files() -> void:
	for p in TOUCHED_PATHS:
		var f = FileAccess.open(p, FileAccess.READ)
		_snapshot[p] = null if f == null else f.get_as_text()
		if f: f.close()

func _restore_user_files() -> void:
	var ok := true
	for p in TOUCHED_PATHS:
		var original = _snapshot.get(p, null)
		if original == null:
			if FileAccess.file_exists(p):
				DirAccess.remove_absolute(ProjectSettings.globalize_path(p))
			if FileAccess.file_exists(p): ok = false
		else:
			var f = FileAccess.open(p, FileAccess.WRITE)
			if f:
				f.store_string(original)
				f.close()
	_check("user:// save data restored", ok)

func _initialize() -> void:
	_table = load("res://control.tscn").instantiate()
	get_root().add_child(_table)

# Readable names — the panels are built in code, so their node names are
# autogenerated and useless in a failure message.
func _open_pickers() -> Array:
	var t = _table
	var out: Array = []
	for pair in [[t.bid_panel, "bid"], [t.trump_panel, "trump"],
			[t.nello_panel, "nello"], [t.nello_exchange_panel, "exchange"]]:
		if is_instance_valid(pair[0]) and pair[0].visible:
			out.append(pair[1])
	return out

func _flags() -> Dictionary:
	var t = _table
	return {
		"bid": t.waiting_for_bid,
		"trump": t.waiting_for_trump,
		"nello": t.waiting_for_nello_mode,
	}

func _process(_delta: float) -> bool:
	_frame += 1
	# Phase 1 — let _ready()/_build_ui() finish.
	if _frame < 4:
		return false
	# Phase 2 — the whole suite, one frame (see header).
	if _frame == 4:
		_snapshot_user_files()
		_run()
		return false
	# Phase 3 — idle so every queue_free() the run triggered actually lands.
	if _frame < 9:
		return false
	_restore_user_files()
	var f = FileAccess.open("res://headless/picker_panel_reset_verify_results.json", FileAccess.WRITE)
	if f:
		f.store_string(JSON.stringify({
			"failures": _failures, "total": _results.size(), "results": _results,
		}, "\t"))
		f.close()
	# quit() carries the exit code; returning true from _process always exits 0,
	# which would report a failing suite as a clean run.
	quit(1 if _failures > 0 else 0)
	return true

# One abandoned picker, one restart, then assert it did not survive.
func _leak_case(label: String, open_it: Callable, panel_name: String, restart: Callable) -> void:
	var t = _table
	open_it.call()
	_check("%s: picker is open before restart" % label,
		_open_pickers().has(panel_name), "open=%s" % str(_open_pickers()))
	restart.call()
	var open_after = _open_pickers()
	_check("%s: does not survive the restart" % label,
		not open_after.has(panel_name), "open=%s" % str(open_after))
	_check("%s: at most one picker open after restart" % label,
		open_after.size() <= 1, "open=%s" % str(open_after))
	_check("%s: stale waiting_for_* cleared" % label,
		not t.waiting_for_trump and not t.waiting_for_nello_mode,
		"flags=%s" % str(_flags()))

func _run() -> void:
	var t = _table
	t.main_menu_panel.visible = false
	t._on_preset_chosen("teel")
	_check("game started", t.game != null)
	if t.game == null:
		return

	var settings_restart := func(): t._restart_game_with_settings(t.game.settings)
	var continue_restart := func(): t._on_hand_continue()

	# ── 1. Reset: the reported path and its siblings ─────────────────────────
	# Settings -> Play is what was reported; the other two prove the hole was
	# never Nello-specific.
	_leak_case("trump via Settings->Play",
		func(): t._show_trump_panel(), "trump", settings_restart)
	_leak_case("nello via Settings->Play",
		func(): t._show_nello_panel(), "nello", settings_restart)
	_leak_case("exchange via Settings->Play",
		func(): t._show_nello_exchange_panel(), "exchange", settings_restart)
	# Next Hand reaches _start_hand() by a different route.
	_leak_case("trump via Next Hand",
		func(): t._show_trump_panel(), "trump", continue_restart)

	# ── 2. Exclusivity: opening any picker closes the others ─────────────────
	t._close_all_pickers()
	t._show_trump_panel()
	t._show_nello_exchange_panel()
	_check("opening the exchange closes the trump panel",
		_open_pickers() == ["exchange"], "open=%s" % str(_open_pickers()))
	t._show_nello_panel()
	_check("opening nello closes the exchange",
		_open_pickers() == ["nello"], "open=%s" % str(_open_pickers()))
	_check("closing trump cleared its flag", not t.waiting_for_trump)

	# ── 3. The self-rebuild trap ─────────────────────────────────────────────
	# _show_bid_panel() re-runs on every "More"/contract-type tap with
	# waiting_for_bid already true and no caller about to set it again. A helper
	# that cleared all flags wholesale would silently end the human's bid turn.
	t._close_all_pickers()
	t.waiting_for_bid = true
	t._show_bid_panel()
	t._show_bid_panel()   # the redraw
	_check("bid panel redraw keeps waiting_for_bid", t.waiting_for_bid)
	_check("bid panel redraw keeps itself open",
		_open_pickers() == ["bid"], "open=%s" % str(_open_pickers()))

	# ── 4. Regression: reset does not fight the next picker ──────────────────
	t._close_all_pickers()
	_check("close-all leaves nothing open", _open_pickers().is_empty(),
		"open=%s" % str(_open_pickers()))
	t._show_trump_panel()
	_check("a picker still opens after close-all",
		_open_pickers() == ["trump"] and t.waiting_for_trump,
		"open=%s" % str(_open_pickers()))

	# ── 5. Regression: the bid-revisit flow still works ──────────────────────
	# It hand-rolls its own close/open pair, so exclusivity must be redundant
	# there rather than disruptive.
	t.game.current_bid = BidScript.new(BidScript.Type.POINTS, 30, t.human_seat)
	t._human_bid_position = 0
	t._bid_before_human = null
	t._revisiting = false
	t._close_all_pickers()
	t._show_trump_panel()
	t._open_bid_revisit("trump")
	_check("revisit opens the bid panel alone",
		_open_pickers() == ["bid"], "open=%s" % str(_open_pickers()))
	_check("revisit keeps waiting_for_bid set", t.waiting_for_bid)
	t._on_revisit_cancelled()
	_check("cancelling revisit returns to the trump panel",
		_open_pickers() == ["trump"], "open=%s" % str(_open_pickers()))
	_check("cancelling revisit clears waiting_for_bid", not t.waiting_for_bid)
