extends SceneTree

# ═══════════════════════════════════════════════════════════════════════════
# Job 6 — Validation for trump_selection_score()/calculate_trump_control_value()
# (Spec: trump_selection_score() and calculate_trump_control_value(), July 20
# 2026). Covers acceptance criteria 6a-6d against the LIVE GDScript, not a
# Python reconstruction — and satisfies the "preserve old vs. new comparison"
# instrumentation request by logging both trump_selection_score()'s
# "selection_score" (new, corrected) and "legacy_selection_score" (old flat
# formula) for every candidate suit of every hand.
#
# Reuses the 40 real hands already generated by Job 5
# (scripts/job5_results.json) — no need to re-run the ~9-minute Monte Carlo
# trick-play simulation again, since only the (cheap, no-simulation) scoring
# formula changed. The ground truth (actual_best_suit / actual_performance,
# from real simulated play) doesn't change; what's being validated here is
# whether the corrected LIVE formula now recommends the suit that ground
# truth already showed was best.
#
# 6a — exact-match regression test on the two named hands (July 20 flagged
#      hand + the Job 5 clean regression hand): confirm best_trump() now
#      returns trump=3 for both, not trump=0.
# 6b — no-regression check across all 40 Job 5 hands: confirm only the one
#      expected hand flips (old chosen_suit vs. new live best_trump() pick).
# 6c — calculate_trump_control_value() smoke test across trump_count
#      {0,3,4,5,6} x has_double_trump {true,false}.
# 6d — the two OTHER known-disagreement hands (realization_shift,
#      no_clear_pattern) must NOT flip — confirmed as part of 6b, called out
#      explicitly here too per the spec's ask.
#
# Run:
#   "$GODOT" --headless --path . --script res://scripts/job6_trump_selection_score_validation.gd
# ═══════════════════════════════════════════════════════════════════════════

var failures: Array = []
var log_lines: Array = []

func _log(s: String):
	log_lines.append(s)
	print(s)

func _check(label: String, condition: bool, detail: String) -> void:
	if condition:
		_log("  PASS: %s — %s" % [label, detail])
	else:
		_log("  FAIL: %s — %s" % [label, detail])
		failures.append(label)

func _tiles_to_hand(tiles: Array) -> Array[Domino]:
	var hand: Array[Domino] = []
	for t in tiles:
		hand.append(Domino.new(t[0], t[1]))
	return hand

# JSON.parse_string() always returns numbers as float, even when the
# original had no decimal point (JSON.stringify() DOES preserve int
# formatting on write, but Godot's parser upcasts everything on read) —
# so a hardcoded int-literal tile array never matches a reparsed one via
# plain Array `==`, even when every value is numerically identical. Compare
# by casting both sides to int explicitly instead of relying on `==`.
func _tiles_equal(a: Array, b: Array) -> bool:
	if a.size() != b.size():
		return false
	for i in range(a.size()):
		if int(a[i][0]) != int(b[i][0]) or int(a[i][1]) != int(b[i][1]):
			return false
	return true

func _init():
	# ── 6a: exact-match regression test on the two named hands ─────────────
	_log("═══════════════════════════════════════════════════════════")
	_log("6a — exact-match regression test")
	_log("═══════════════════════════════════════════════════════════")

	var flagged_hand_tiles = [[6,6],[3,4],[1,6],[4,4],[0,5],[2,2],[3,3]]  # July 20 flagged hand
	var job5_regression_tiles = [[1,3],[0,6],[0,3],[6,6],[1,1],[4,4],[3,3]]  # Job 5 clean regression hand

	var flagged_result = AIPlayer.best_trump(_tiles_to_hand(flagged_hand_tiles))
	_check("6a_flagged_hand_now_picks_trump_3", flagged_result["trump"] == 3,
		"best_trump() returned trump=%d (selection_score=%.3f, legacy=%.3f)" % [
			flagged_result["trump"], flagged_result["selection_score"], flagged_result["legacy_selection_score"]])

	var regression_result = AIPlayer.best_trump(_tiles_to_hand(job5_regression_tiles))
	_check("6a_job5_regression_hand_now_picks_trump_3", regression_result["trump"] == 3,
		"best_trump() returned trump=%d (selection_score=%.3f, legacy=%.3f)" % [
			regression_result["trump"], regression_result["selection_score"], regression_result["legacy_selection_score"]])

	# ── 6c: calculate_trump_control_value() smoke test ──────────────────────
	_log("")
	_log("═══════════════════════════════════════════════════════════")
	_log("6c — calculate_trump_control_value() smoke test")
	_log("═══════════════════════════════════════════════════════════")
	# Expected values hand-derived from the tier definition: +2.5 if double,
	# +1.5 if >=4, +3.0 if >=5 (additional), +2.0 if >=6 (additional).
	var expected_cv := {
		"0_false": 0.0, "0_true": 2.5,
		"3_false": 0.0, "3_true": 2.5,
		"4_false": 1.5, "4_true": 4.0,
		"5_false": 4.5, "5_true": 7.0,
		"6_false": 6.5, "6_true": 9.0,
	}
	for trump_count in [0, 3, 4, 5, 6]:
		for has_double in [false, true]:
			var key = "%d_%s" % [trump_count, str(has_double)]
			var actual = AIPlayer.calculate_trump_control_value(trump_count, has_double)
			_check("6c_control_value_%s" % key, is_equal_approx(actual, expected_cv[key]),
				"trump_count=%d has_double_trump=%s -> expected %.1f, got %.3f" % [trump_count, has_double, expected_cv[key], actual])

	# ── 6b / 6d: reuse Job 5's 40 hands, compare old chosen_suit (recorded)
	# against the NEW live best_trump() pick, and log old-vs-new scores for
	# every candidate of every hand (side-by-side comparison instrumentation).
	_log("")
	_log("═══════════════════════════════════════════════════════════")
	_log("6b/6d — rerun against all 40 Job 5 hands (live GDScript, not Python)")
	_log("═══════════════════════════════════════════════════════════")

	var f_in = FileAccess.open("res://scripts/job5_results.json", FileAccess.READ)
	if f_in == null:
		_log("  FAIL: could not open scripts/job5_results.json — run Job 5 first")
		failures.append("job5_results_missing")
		_finish({})
		return
	var job5_data = JSON.parse_string(f_in.get_as_text())
	f_in.close()

	var comparison_records := []
	var n_flipped := 0
	var flipped_hands := []
	var known_disagreement_hands = {
		# tag -> bidder_hand tiles, for explicit 6d naming
		"realization_shift": [[1,6],[5,5],[2,5],[4,4],[3,3],[4,6],[0,5]],
		"no_clear_pattern": [[4,4],[5,5],[2,2],[1,4],[2,5],[3,3],[1,1]],
	}

	for rec in job5_data["hands"]:
		var tiles = rec["bidder_hand"]
		var hand = _tiles_to_hand(tiles)
		var old_chosen = rec["chosen_suit"]

		# Full per-suit old-vs-new comparison (the instrumentation deliverable).
		var per_suit := []
		for suit in range(7):
			var r = AIPlayer.trump_selection_score(hand, suit)
			per_suit.append({
				"trump": suit,
				"legacy_selection_score": r["legacy_selection_score"],
				"selection_score": r["selection_score"],
				"corrected_estimated_points": r["corrected_estimated_points"],
				"control_value": r["control_value"],
			})

		var new_result = AIPlayer.best_trump(hand)
		var new_chosen = new_result["trump"]
		var flipped = (new_chosen != old_chosen)
		if flipped:
			n_flipped += 1
			flipped_hands.append({"bidder_hand": tiles, "old_chosen": old_chosen, "new_chosen": new_chosen})

		comparison_records.append({
			"bidder_hand": tiles,
			"old_chosen_suit": old_chosen,
			"new_chosen_suit": new_chosen,
			"flipped": flipped,
			"per_suit_scores": per_suit,
		})

	_check("6b_exactly_one_hand_flips", n_flipped == 1,
		"expected exactly 1 flip (the Job 5 regression hand), got %d: %s" % [n_flipped, flipped_hands])

	if n_flipped >= 1:
		var only_flip = flipped_hands[0]
		_check("6b_the_one_flip_is_the_expected_regression_hand",
			_tiles_equal(only_flip["bidder_hand"], job5_regression_tiles) and only_flip["new_chosen"] == 3,
			"flipped hand: %s (old=%d -> new=%d)" % [only_flip["bidder_hand"], only_flip["old_chosen"], only_flip["new_chosen"]])

	# 6d — explicitly confirm the two OTHER known-disagreement hands did NOT flip.
	for tag in known_disagreement_hands:
		var tiles = known_disagreement_hands[tag]
		var hand = _tiles_to_hand(tiles)
		var new_result = AIPlayer.best_trump(hand)
		var matching_rec = null
		for rec in job5_data["hands"]:
			if _tiles_equal(rec["bidder_hand"], tiles):
				matching_rec = rec
				break
		if matching_rec == null:
			_log("  FAIL: could not find %s hand %s in job5 data" % [tag, tiles])
			failures.append("6d_%s_hand_not_found" % tag)
			continue
		_check("6d_%s_still_unfixed" % tag, new_result["trump"] == matching_rec["chosen_suit"],
			"expected chosen suit to remain %d (unchanged), got %d — %s%s" % [
				matching_rec["chosen_suit"], new_result["trump"],
				"UNEXPECTED FLIP, worth investigating" if new_result["trump"] != matching_rec["chosen_suit"] else "still an open disagreement, as expected",
				""])

	_finish({
		"n_hands": comparison_records.size(),
		"n_flipped": n_flipped,
		"flipped_hands": flipped_hands,
		"per_hand_comparison": comparison_records,
	})

func _finish(job5_comparison: Dictionary):
	_log("")
	_log("═══════════════════════════════════════════════════════════")
	if failures.is_empty():
		_log("ALL CHECKS PASSED")
	else:
		_log("FAILURES: %s" % [failures])
	_log("═══════════════════════════════════════════════════════════")

	var output = {
		"failures": failures,
		"job5_comparison": job5_comparison,
		"full_log": log_lines,
	}
	var f = FileAccess.open("res://scripts/job6_results.json", FileAccess.WRITE)
	f.store_string(JSON.stringify(output, "\t"))
	f.close()

	print("")
	print("Results written to res://scripts/job6_results.json")
	quit(0 if failures.is_empty() else 1)
